#!/usr/bin/env python3
"""Build the reader handbook and graph-source mirrors from canonical website Markdown.

Coverage scans web/handbook/guides and skills non-recursively. Canonical pack command
names and knowledge basenames are the required token sets; FOUNDATION is provenance,
not a knowledge capability. No other content tree is admitted to the public corpus.
"""
import argparse
import hashlib
import html
import json
from pathlib import Path
import re
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
MARKER = "<!-- Generated by tools/build-handbook.py; edit web/handbook sources. -->"
PARSER_SHA = "21568877a938d2c4e7d74e27f18e60da96bb73a68809610ca39216e1efebae62"
SECTIONS = ("When to use it", "What you need", "Try it", "What happens",
            "What you get", "Review before continuing", "Tips and recovery", "Where to go next")

for stream in (sys.stdout, sys.stderr):
    if hasattr(stream, "reconfigure"):
        stream.reconfigure(encoding="utf-8", errors="replace")


def require(condition, code, detail):
    if not condition:
        raise ValueError(f"{code}: {detail}")


def read_source(path, root):
    require(path.is_file() and not path.is_symlink() and path.resolve() == path.absolute(),
            "HANDBOOK-SOURCE-ALIAS", str(path.relative_to(root)))
    return path.read_text(encoding="utf-8")


def sections(markdown):
    """Extract real H2 sections without treating example code as document structure."""
    result, name, fence = {}, None, None
    for line in markdown.splitlines():
        marker = re.match(r"^\s*(`{3,}|~{3,})", line)
        if marker:
            token = marker.group(1)
            if fence is None:
                fence = token
            elif token[0] == fence[0] and len(token) >= len(fence):
                fence = None
        heading = re.match(r"^## (.+)$", line) if fence is None else None
        if heading:
            name = heading.group(1).strip()
            require(name not in result, "HANDBOOK-CONTENT", f"duplicate section {name}")
            result[name] = []
        elif name is not None:
            result[name].append(line)
    return {key: "\n".join(value).strip() for key, value in result.items()}


def plain(text):
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    return re.sub(r"\s+", " ", re.sub(r"[`*_]", "", text)).strip()


def graph_markdown(page, manifest, body=None):
    related = "architecture" if page["id"] == "overview" else "handbook-" + page["guide"]
    record = {
        "id": "handbook-" + page["id"], "title": page["title"], "type": "doc",
        "status": "accepted", "owner": manifest["owner"], "phase": "documentation",
        "review-by": manifest["review_by"], "summary": page["summary"],
    }
    front = "\n".join(f"{key}: {json.dumps(value, ensure_ascii=False)}" for key, value in record.items())
    return (f"---\n{front}\ntags: [handbook, reader-guide]\n"
            f"links:\n  - {{ to: {related}, rel: relates-to }}\n---\n\n"
            f"{MARKER}\n\n{body if body is not None else page['markdown']}\n")


def build(root):
    """Return deterministic output bytes as text and observable coverage counts."""
    root = Path(root).resolve()
    source = root / "web" / "handbook"
    manifest = json.loads(read_source(source / "navigation.json", root))
    require(manifest.get("schema") == "ai-forward-handbook/1",
            "HANDBOOK-MANIFEST", "unsupported navigation schema")
    guide_order = [slug for group in manifest["groups"] for slug in group["pages"]]
    guide_files = {p.stem: p for p in (source / "guides").glob("*.md")}
    require(len(guide_order) == len(set(guide_order)) and set(guide_order) == set(guide_files),
            "HANDBOOK-NAV", "every guide needs exactly one navigation home")
    expected = {p.parent.name for p in (root / "pack" / "commands").glob("*/SKILL.md")}
    skill_files = {p.stem: p for p in (source / "skills").glob("*.md")}
    listed = [skill for group in manifest["skill_groups"] for skill in group["skills"]]
    require(set(skill_files) == expected == set(listed) and len(listed) == len(set(listed)),
            "HANDBOOK-SKILL-COVERAGE",
            f"missing={sorted(expected - set(skill_files))}; extra={sorted(set(skill_files) - expected)}")
    knowledge = {p.stem for p in (root / "pack" / "knowledge").glob("*.md") if p.stem != "FOUNDATION"}
    covered = {name for area in manifest["capabilities"] for name in area["sources"]}
    require(knowledge == covered, "HANDBOOK-KNOWLEDGE-COVERAGE",
            f"missing={sorted(knowledge - covered)}; extra={sorted(covered - knowledge)}")
    require(all(area["guide"] in guide_files for area in manifest["capabilities"]),
            "HANDBOOK-NAV", "capability guide is missing")
    pages, skill_coverage = [], []
    group_of = {slug: group["title"] for group in manifest["groups"] for slug in group["pages"]}
    skill_group = {name: group for group in manifest["skill_groups"] for name in group["skills"]}
    for kind, names, files in (("guide", guide_order, guide_files), ("skill", sorted(expected), skill_files)):
        for name in names:
            slug = "skill-" + name if kind == "skill" else name
            require(bool(re.fullmatch(r"[a-z][a-z0-9-]*", slug)),
                    "HANDBOOK-NAV", "invalid page identifier")
            markdown = read_source(files[name], root).replace("\r\n", "\n").strip()
            first = re.match(r"^# ([^\n]+)\n\n(.+?)(?:\n\n|$)", markdown, re.S)
            require(first is not None, "HANDBOOK-CONTENT", f"{slug} needs a title and introduction")
            title, summary = plain(first.group(1)), plain(first.group(2))
            guide = skill_group[name]["guide"] if kind == "skill" else "overview"
            page = {"id": slug, "title": title, "summary": summary, "markdown": markdown,
                    "kind": kind, "skill": name if kind == "skill" else None, "guide": guide,
                    "group": skill_group[name]["title"] if kind == "skill" else group_of[name]}
            pages.append(page)
            if kind == "skill":
                parts = sections(markdown)
                require(all(parts.get(section) for section in SECTIONS), "HANDBOOK-CONTENT",
                        f"{name} is missing a substantive required section")
                example = re.search(r"```[^\n]*\n(.*?)```", parts["Try it"], re.S)
                require(example is not None, "HANDBOOK-CONTENT", f"{name} needs an invocation example")
                skill_coverage.append({
                    "skill": name, "problem": summary, "reader": skill_group[name]["reader"],
                    "prerequisites": plain(parts["What you need"]), "guide_home": "#" + guide,
                    "reference_home": "#" + slug, "example": example.group(1).strip(),
                    "scope_limits": plain(parts["Tips and recovery"] + "\n" + parts["Review before continuing"]),
                    "source_contract": f"pack/commands/{name}/SKILL.md",
                })
    ids = {page["id"] for page in pages}
    aliases = manifest["aliases"]
    require(not (set(aliases) & ids) and all(value in ids for value in aliases.values()),
            "HANDBOOK-NAV", "aliases must resolve without shadowing a page")
    for page in pages:
        links = re.findall(r"\]\((#[^)]+)\)", page["markdown"])
        require(all(link[1:].split("--", 1)[0] in ids | set(aliases) for link in links),
                "HANDBOOK-LINK", f"unresolved handbook link in {page['id']}")
    parser = read_source(source / "vendor" / "marked.umd.js", root)
    require(hashlib.sha256(parser.encode("utf-8")).hexdigest() == PARSER_SHA,
            "HANDBOOK-DEPENDENCY", "vendored marked bytes differ from the recorded version")
    require((source / "vendor" / "marked-LICENSE.txt").is_file(),
            "HANDBOOK-DEPENDENCY", "vendored license is missing")
    data = {"schema": manifest["schema"], "pages": pages, "groups": manifest["groups"],
            "skill_groups": manifest["skill_groups"], "aliases": aliases}
    encoded = json.dumps(data, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")
    template = read_source(source / "template.html", root)
    replacements = {
        "__HANDBOOK_DATA__": encoded,
        "__HANDBOOK_CSS__": read_source(source / "handbook.css", root),
        "__HANDBOOK_JS__": read_source(source / "handbook.js", root),
        "__MARKED_JS__": parser.replace("</script", "<\\/script"),
        "__START_TITLE__": html.escape(pages[0]["title"]),
        "__START_SUMMARY__": html.escape(pages[0]["summary"]),
    }
    for token, value in replacements.items():
        require(template.count(token) == 1, "HANDBOOK-TEMPLATE", f"missing or duplicate slot {token}")
        template = template.replace(token, value)
    require(len(template.encode("utf-8")) < 1024 * 1024, "HANDBOOK-PAYLOAD", "embedded page exceeds 1 MiB")
    outputs = {"docs/portal/index.html": template}
    for page in pages:
        outputs[f"docs/handbook/{page['id']}.md"] = graph_markdown(page, manifest)
    coverage = {"schema": "handbook-coverage/1", "skills": skill_coverage,
                "capabilities": manifest["capabilities"]}
    outputs["docs/handbook/coverage.json"] = json.dumps(coverage, indent=2, ensure_ascii=False) + "\n"
    rows = ["# Handbook coverage", "", "This generated maintenance map links each current skill to its reader-facing home.",
            "", "| Skill | Reader | Problem | Guide | Reference |", "|---|---|---|---|---|"]
    for row in skill_coverage:
        problem = row["problem"].replace("|", "\\|")
        rows.append(f"| {row['skill']} | {row['reader']} | {problem} | "
                    f"[Guide](../portal/index.html{row['guide_home']}) | "
                    f"[Reference](../portal/index.html{row['reference_home']}) |")
    rows.extend(["", "The companion JSON also records prerequisites, example input, limits and the canonical source contract.",
                 "", "## Capability homes", "", "| Capability | Guide | Source standards |", "|---|---|---|"])
    for area in manifest["capabilities"]:
        rows.append(f"| {area['name']} | [Guide](../portal/index.html#{area['guide']}) | "
                    + ", ".join(area["sources"]) + " |")
    outputs["docs/handbook/coverage.md"] = graph_markdown(
        {"id": "coverage", "title": "Handbook coverage", "summary": "Reader-oriented coverage of every current skill and knowledge area.",
         "guide": "overview", "markdown": ""}, manifest, "\n".join(rows))
    report = {"pages": len(pages), "skills": len(expected), "knowledge_docs": len(knowledge),
              "html_bytes": len(template.encode("utf-8"))}
    return outputs, report


def main():
    parser = argparse.ArgumentParser(description="Generate or check the reader-first handbook and coverage map.")
    parser.add_argument("--check", action="store_true", help="report drift without changing any file")
    args = parser.parse_args()
    started = time.monotonic()
    try:
        outputs, report = build(ROOT)
        stale = [name for name, text in outputs.items()
                 if not (ROOT / name).is_file() or (ROOT / name).read_text(encoding="utf-8") != text]
        extras = [path for path in (ROOT / "docs" / "handbook").glob("*")
                  if path.is_file() and path.relative_to(ROOT).as_posix() not in outputs]
        if args.check:
            report.update(code="HANDBOOK-DRIFT" if stale or extras else "HANDBOOK-CURRENT",
                          changed=stale, extra=[p.relative_to(ROOT).as_posix() for p in extras])
        else:
            for path in extras:
                require(MARKER in path.read_text(encoding="utf-8"), "HANDBOOK-UNMANAGED",
                        f"refuse to remove {path.relative_to(ROOT)}")
                path.unlink()
            for name, text in outputs.items():
                path = ROOT / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8", newline="\n")
            report.update(code="HANDBOOK-BUILT", changed=stale)
        report["duration_seconds"] = round(time.monotonic() - started, 3)
        print(json.dumps(report, ensure_ascii=True))
        return 1 if args.check and (stale or extras) else 0
    except (OSError, ValueError, KeyError, TypeError) as error:
        print(json.dumps({"code": "HANDBOOK-BUILD-FAILED", "detail": str(error)}, ensure_ascii=True), file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
